  CREATE TABLE "TBG"."LNE_ACCOUNTS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"MODULE" VARCHAR2(30 CHAR), 
	"BRANCH" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"AGR_NO" NUMBER NOT NULL ENABLE, 
	"ACC_CODE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"START_DATE" DATE NOT NULL ENABLE, 
	"ACC_ID" VARCHAR2(25 CHAR) NOT NULL ENABLE, 
	"AGR_FLAG" VARCHAR2(1 CHAR), 
	"UPDATED" TIMESTAMP (6) DEFAULT LOCALTIMESTAMP, 
	"UPDATED_BY" VARCHAR2(30 CHAR) DEFAULT coalesce(sys_context('userenv','client_identifier'), user), 
	"CREATED" TIMESTAMP (6) DEFAULT LOCALTIMESTAMP, 
	"CREATED_BY" VARCHAR2(30 CHAR) DEFAULT coalesce(sys_context('userenv','client_identifier'), user), 
	"ACCT_ID" NUMBER, 
	"PATTERN" VARCHAR2(30 CHAR), 
	"PATTERN_TYPE" VARCHAR2(1 CHAR), 
	"OPER_NO" NUMBER, 
	 CONSTRAINT "LNE_ACCOUNTS_PK" PRIMARY KEY ("ID")
    ) 
  TABLESPACE "TS_BELL_TABLE" ;

   COMMENT ON COLUMN "TBG"."LNE_ACCOUNTS"."MODULE" IS 'Имя модуля (ЯДРО, КРЕДИТЫ, ДЕПОЗИТЫ и т. д.).';
   COMMENT ON COLUMN "TBG"."LNE_ACCOUNTS"."BRANCH" IS 'Код филиала.';
   COMMENT ON COLUMN "TBG"."LNE_ACCOUNTS"."AGR_NO" IS 'Внутренний номер договора.';
   COMMENT ON COLUMN "TBG"."LNE_ACCOUNTS"."ACC_CODE" IS 'Код типа счета из таблицы T_Cr_Acc_Type.';
   COMMENT ON COLUMN "TBG"."LNE_ACCOUNTS"."START_DATE" IS 'Дата, начиная с которой, остатки на счете правильные.';
   COMMENT ON COLUMN "TBG"."LNE_ACCOUNTS"."ACC_ID" IS 'Номер счета.';
   COMMENT ON COLUMN "TBG"."LNE_ACCOUNTS"."AGR_FLAG" IS 'Флаг привязки к договору, если NULL - счет обслуживает несколько договоров.';
   COMMENT ON COLUMN "TBG"."LNE_ACCOUNTS"."UPDATED" IS 'Дата изменения записи.';
   COMMENT ON COLUMN "TBG"."LNE_ACCOUNTS"."UPDATED_BY" IS 'Пользователь, занесший изменения в запись.';
   COMMENT ON COLUMN "TBG"."LNE_ACCOUNTS"."ACCT_ID" IS 'уникальный идентификатор счета';
   COMMENT ON COLUMN "TBG"."LNE_ACCOUNTS"."PATTERN" IS 'Прототип, по которому открыт счет';
   COMMENT ON COLUMN "TBG"."LNE_ACCOUNTS"."PATTERN_TYPE" IS 'вид прототипа';
   COMMENT ON COLUMN "TBG"."LNE_ACCOUNTS"."OPER_NO" IS 'Ссылка на операцию, в рамках которой создан счёт';
   COMMENT ON TABLE "TBG"."LNE_ACCOUNTS"  IS 'Таблица счетов кредитных договоров.';


  CREATE TABLE "TBG"."LNE_ACC_PATTERN_TYPE_C" 
   (	"PATTERN_TYPE_C" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"NAME" VARCHAR2(256 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(256 CHAR), 
	"ACCT_OPEN_FLAG" VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL ENABLE, 
	 CONSTRAINT "LNE_ACC_PATTERN_TYPE_C_PK" PRIMARY KEY ("PATTERN_TYPE_C")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_BELL_TABLE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_BELL_TABLE" ;

   COMMENT ON TABLE "TBG"."LNE_ACC_PATTERN_TYPE_C"  IS 'Справочник типов шаблонов счетов';




  CREATE TABLE "TBG"."LNE_ACCT_BAL_TYPE_C" 
   (	"BAL_TYPE_C" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"NAME" VARCHAR2(256 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(256 CHAR), 
	 CONSTRAINT "LNE_ACCT_BAL_TYPE_C_PK" PRIMARY KEY ("BAL_TYPE_C")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_BELL_TABLE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_BELL_TABLE" ;

   COMMENT ON TABLE "TBG"."LNE_ACCT_BAL_TYPE_C"  IS 'Виды учета на балансовых или внебалансовых счетах';


  CREATE TABLE "TBG"."LNE_ACCT_TYPE" 
   (	"MODULE" VARCHAR2(30 CHAR), 
	"CODE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"DESCR" VARCHAR2(240 CHAR), 
	"BASE" VARCHAR2(30 CHAR), 
	"INT" VARCHAR2(30 CHAR), 
	"CALC_BASE" VARCHAR2(30 CHAR), 
	"CALC_INT" VARCHAR2(30 CHAR), 
	"UPDATED" TIMESTAMP (6) DEFAULT LOCALTIMESTAMP, 
	"UPDATED_BY" VARCHAR2(30 CHAR) DEFAULT coalesce(sys_context('userenv','client_identifier'), user), 
	"AGR_FLAG" VARCHAR2(1 CHAR), 
	"RES_FLAG" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"OPEN_FLAG" VARCHAR2(1 CHAR) DEFAULT 'Y', 
	"COPY_CODE" VARCHAR2(30 CHAR), 
	"ACC_DEL" VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL ENABLE, 
	"PR_COM_CODE" VARCHAR2(30 CHAR), 
	"AVG_PAY_FLAG" VARCHAR2(1 CHAR) DEFAULT 'N', 
	 CONSTRAINT "LNE_ACCT_TYPE_PK" PRIMARY KEY ("CODE")
   ) ;

   COMMENT ON COLUMN "TBG"."LNE_ACCT_TYPE"."MODULE" IS 'Имя модуля (ЯДРО, КРЕДИТЫ, ДЕПОЗИТЫ и т. д.).';
   COMMENT ON COLUMN "TBG"."LNE_ACCT_TYPE"."CODE" IS 'Код типа счета.';
   COMMENT ON COLUMN "TBG"."LNE_ACCT_TYPE"."DESCR" IS 'Название типа счета.';
   COMMENT ON COLUMN "TBG"."LNE_ACCT_TYPE"."BASE" IS 'Код типа базового счета, если это счет уплаченных процентов.';
   COMMENT ON COLUMN "TBG"."LNE_ACCT_TYPE"."INT" IS 'Код типа счета уплаченных процентов, если это базовый счет.';
   COMMENT ON COLUMN "TBG"."LNE_ACCT_TYPE"."CALC_BASE" IS 'Код типа базового счета, если это счет начисленных процентов.';
   COMMENT ON COLUMN "TBG"."LNE_ACCT_TYPE"."CALC_INT" IS 'Код типа счета начисленных процентов, если это базовый счет.';
   COMMENT ON COLUMN "TBG"."LNE_ACCT_TYPE"."UPDATED" IS 'Дата изменения записи.';
   COMMENT ON COLUMN "TBG"."LNE_ACCT_TYPE"."UPDATED_BY" IS 'Пользователь, занесший изменения в запись.';
   COMMENT ON COLUMN "TBG"."LNE_ACCT_TYPE"."RES_FLAG" IS 'Признак типа счета резервирования';
   COMMENT ON COLUMN "TBG"."LNE_ACCT_TYPE"."OPEN_FLAG" IS 'Признак отдельного открытия счета (Y - счет открывается, N - счет копируется из счета с лог. именем из поля copy_code)';
   COMMENT ON COLUMN "TBG"."LNE_ACCT_TYPE"."COPY_CODE" IS 'Код типа счета для копирования';
   COMMENT ON COLUMN "TBG"."LNE_ACCT_TYPE"."ACC_DEL" IS 'Признак проверки счета перед удалением (Y - удаляем без прочих проверок, N - выполняем проверки)';
   COMMENT ON COLUMN "TBG"."LNE_ACCT_TYPE"."PR_COM_CODE" IS 'Код счета просроченной комиссии, соответствующий коду счета начисленной комиссии';
   COMMENT ON COLUMN "TBG"."LNE_ACCT_TYPE"."AVG_PAY_FLAG" IS 'флаг счета по просрочке для среднего платежа';
   COMMENT ON TABLE "TBG"."LNE_ACCT_TYPE"  IS 'Справочник типов счетов кредитных договоров.';
