SELECT * FROM TBG.LNE_SCHEDULE_HIST WHERE HIST_ID = 4;
SELECT * FROM TBG.LNE_SCHEDULE WHERE SCHED_ID = 1582829;
SELECT * FROM TBG.LNE_RATE WHERE RATE_ID = 1334211;
SELECT * FROM TBG.LNE_OPERATION_CHARGED WHERE OPER_ID = 313420;
SELECT * FROM TBG.LNE_OPERATION WHERE OPER_NO = 6422;
SELECT * FROM TBG.LNE_CONDITIONS WHERE COND_ID = 2;
SELECT * FROM TBG.LNE_COLLAT_INSURANCE WHERE INS_ID = 68;
SELECT * FROM TBG.LNE_COLLATERAL_ITEM where NO = 211;
SELECT * FROM TBG.LNE_COLLATERAL where NO = 6;
select * from TBG.LNE_AGREEMENTS where AGR_NO = 16546;
select * from TBG.LNE_ACCOUNTS where ID = 2;


select count(*) from TBG.LNE_AGR_PURPOSE;
select * from TBG.LNE_AGR_PURPOSE;
select * from TBG.LNE_AGR_PURPOSE where ID = 4220;


drop table "TBG"."LNE_AGR_PURPOSE";

  CREATE TABLE "TBG"."LNE_AGR_PURPOSE" 
   (	"BRANCH" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"AGR_NO" NUMBER NOT NULL ENABLE, 
	"SUM" NUMBER NOT NULL ENABLE, 
	"PURPOSE_CODE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"REMARKS" VARCHAR2(240 CHAR), 
	"MAIN_PURPOSE" VARCHAR2(1 CHAR), 
	"CREATED" TIMESTAMP (6) DEFAULT LOCALTIMESTAMP, 
	"CREATED_BY" VARCHAR2(30 CHAR) DEFAULT coalesce(sys_context('userenv','client_identifier'), user), 
	"UPDATED" TIMESTAMP (6) DEFAULT LOCALTIMESTAMP, 
	"UPDATED_BY" VARCHAR2(30 CHAR) DEFAULT coalesce(sys_context('userenv','client_identifier'), user), 
	"ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "LNE_AGR_PURPOSE_PK" PRIMARY KEY ("ID")
   ) ;

grant insert, update, delete on "TBG"."LNE_AGR_PURPOSE" to tbg;

select 
    BRANCH, AGR_NO, START_DATE, SCHEDULE_TYPE_C, REMAINDER, PARENT_DATE, DOSR_DATE, UPDATED, UPDATED_BY, PRC_CALC_MODE, 
    SCHED_TYPE, EFFECT_RATE, PSK, ACT_PAY_FLAG, GR_CODE, EFFECT_RATE_2, LOST_INCOME, PRC_CALC_DATE, EXT_FLAG, EDIT_COND, 
    EDIT_PSK, EP, MIDDLE_PAYMENT, RESTRUCT_FLAG, INDIV_PSK, HDR_ID, LAST_PMT_DATE
from "PROKUNIN_DBA"."LNE_SCHEDULE_HDR";

select AGR_NO, START_DATE from "PROKUNIN_DBA"."LNE_SCHEDULE_HDR";


select count(*) from "PROKUNIN_DBA"."LNE_SCHEDULE_HDR";
select count(*) from "TBG"."LNE_SCHEDULE_HDR";
select * from "TBG"."LNE_SCHEDULE_HDR" where agr_no=33442;

desc "PROKUNIN_DBA"."LNE_SCHEDULE_HDR";
drop table "PROKUNIN_DBA"."LNE_SCHEDULE_HDR";
CREATE TABLE "PROKUNIN_DBA"."LNE_SCHEDULE_HDR" 
   (	"BRANCH" VARCHAR2(8 CHAR), 
	"AGR_NO" NUMBER NOT NULL ENABLE, 
	"START_DATE" DATE NOT NULL ENABLE, 
	"SCHEDULE_TYPE_C" VARCHAR2(30 CHAR), 
	"REMAINDER" NUMBER, 
	"PARENT_DATE" DATE, 
	"DOSR_DATE" DATE, 
	"UPDATED" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(30 CHAR), 
	"PRC_CALC_MODE" VARCHAR2(30 CHAR), 
	"SCHED_TYPE" VARCHAR2(30 CHAR), 
	"EFFECT_RATE" NUMBER, 
	"PSK" NUMBER, 
	"ACT_PAY_FLAG" VARCHAR2(1 CHAR), 
	"GR_CODE" VARCHAR2(30 CHAR), 
	"EFFECT_RATE_2" NUMBER, 
	"LOST_INCOME" VARCHAR2(1 CHAR), 
	"PRC_CALC_DATE" DATE, 
	"EXT_FLAG" VARCHAR2(1 CHAR), 
	"EDIT_COND" VARCHAR2(1 CHAR), 
	"EDIT_PSK" VARCHAR2(1 CHAR), 
	"EP" NUMBER, 
	"MIDDLE_PAYMENT" NUMBER, 
	"RESTRUCT_FLAG" VARCHAR2(1 CHAR), 
	"INDIV_PSK" VARCHAR2(1 CHAR), 
	"HDR_ID" NUMBER NOT NULL ENABLE, 
	"LAST_PMT_DATE" DATE, 
	 CONSTRAINT "LNE_SCHEDULE_HDR_PK" PRIMARY KEY ("AGR_NO", "START_DATE")
   ) ;

CREATE UNIQUE INDEX "PROKUNIN_DBA"."LNE_SCHEDULE_HDR_UK1" ON "PROKUNIN_DBA"."LNE_SCHEDULE_HDR" ("HDR_ID")

desc "PROKUNIN_DBA"."LNE_SCHEDULE_HDR" 
truncate table  "PROKUNIN_DBA"."LNE_SCHEDULE_HDR";
commit
drop table PROKUNIN_DBA.TST_TAB;
/*
create table PROKUNIN_DBA.TST_TAB
(
  col1     integer      not null,
  col2	   varchar2(20),
  PRIMARY KEY(col1)
);
*/
CREATE TABLE "PROKUNIN_DBA"."TST_TAB" 
   (	"COL1" NUMBER(*,0) NOT NULL ENABLE, 
	"COL2" VARCHAR2(10 CHAR), 
	 PRIMARY KEY ("COL1")
); 
grant insert, update, delete on prokunin_dba.tst_tab to tbg;
select * from prokunin_dba.tst_tab;
truncate table prokunin_dba.tst_tab;


alter table TBG.LNE_SCHEDULE_HDR rename to LNE_SCHEDULE_HDR_OLD;
ALTER TABLE TBG.LNE_SCHEDULE_HDR drop   CONSTRAINT LNE_SCHEDULE_HDR_PK
commit;

select * from TBG.LNE_SCHEDULE_HDR_OLD;

--DROP TABLE TBG.LNE_SCHEDULE_HDR CASCADE CONSTRAINTS;

CREATE TABLE TBG.LNE_SCHEDULE_HDR
(
  BRANCH           VARCHAR2(8 CHAR)             NOT NULL,
  AGR_NO           NUMBER                       NOT NULL,
  START_DATE       DATE                         NOT NULL,
  SCHEDULE_TYPE_C  VARCHAR2(30 CHAR)            NOT NULL,
  REMAINDER        NUMBER                       NOT NULL,
  PARENT_DATE      DATE,
  DOSR_DATE        DATE,
  UPDATED          TIMESTAMP(6)                 DEFAULT LOCALTIMESTAMP,
  UPDATED_BY       VARCHAR2(30 CHAR)            DEFAULT coalesce(sys_context('userenv','client_identifier'), user),
  PRC_CALC_MODE    VARCHAR2(30 CHAR),
  SCHED_TYPE       VARCHAR2(30 CHAR),
  EFFECT_RATE      NUMBER,
  PSK              NUMBER,
  ACT_PAY_FLAG     VARCHAR2(1 CHAR)             DEFAULT 'N'                   NOT NULL,
  GR_CODE          VARCHAR2(30 CHAR),
  EFFECT_RATE_2    NUMBER,
  LOST_INCOME      VARCHAR2(1 CHAR)             DEFAULT 'N'                   NOT NULL,
  PRC_CALC_DATE    DATE,
  EXT_FLAG         VARCHAR2(1 CHAR)             DEFAULT 'N'                   NOT NULL,
  EDIT_COND        VARCHAR2(1 CHAR)             DEFAULT 'N',
  EDIT_PSK         VARCHAR2(1 CHAR)             DEFAULT 'N',
  EP               NUMBER,
  MIDDLE_PAYMENT   NUMBER,
  RESTRUCT_FLAG    VARCHAR2(1 CHAR)             DEFAULT 'N',
  INDIV_PSK        VARCHAR2(1 CHAR)             DEFAULT 'N',
  HDR_ID           NUMBER                       DEFAULT null                  NOT NULL,
  LAST_PMT_DATE    DATE
)
;

COMMENT ON TABLE TBG.LNE_SCHEDULE_HDR IS 'Таблица истории заголовка графиков погашения.';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.BRANCH IS 'Код филиала.';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.AGR_NO IS 'Внутренний номер договора.';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.START_DATE IS 'Дата, с которой начинает действовать график погашения.';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.SCHEDULE_TYPE_C IS 'Код операции (пролонгация, выдача ссуды, изменение графика).';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.REMAINDER IS 'Остаток ссуды на момент построения графика.';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.UPDATED IS 'Дата изменения записи.';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.UPDATED_BY IS 'Пользователь, занесший изменения в запись.';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.PRC_CALC_MODE IS 'DEPRECATED';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.SCHED_TYPE IS 'Тип построения графика(ONE,MANY,ANNUITET)';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.EFFECT_RATE IS 'Эффективная ставка';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.PSK IS 'ПСК';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.ACT_PAY_FLAG IS 'Признак актуального для текущих расчетов графика';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.GR_CODE IS 'Тип ставки для расчета ПСК с учетом выпадающих доходов';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.EFFECT_RATE_2 IS 'Эффективная ставка  с учетом выпадающих доходов';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.LOST_INCOME IS 'флаг расчета по ставке для выпадающих доходов';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.PRC_CALC_DATE IS 'Дата начала расчета %%';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.EXT_FLAG IS 'Признак загрузки графика извне';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.EDIT_COND IS 'Признак ручного редактирования графика';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.EDIT_PSK IS 'Признак редактирования ПСК';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.EP IS 'сумма ежемесячного платежа(ссуда+%% для аннуитета, ссуда для дифференцированного)';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.MIDDLE_PAYMENT IS 'Средний платеж';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.RESTRUCT_FLAG IS 'Признак реструктуризации';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.INDIV_PSK IS 'Признак расчета ПСК для индивидуального графика';

COMMENT ON COLUMN TBG.LNE_SCHEDULE_HDR.LAST_PMT_DATE IS 'Дата последнего платежа по ОД';


CREATE UNIQUE INDEX TBG.LNE_SCHEDULE_HDR_PK ON TBG.LNE_SCHEDULE_HDR (AGR_NO, START_DATE);


ALTER TABLE TBG.LNE_SCHEDULE_HDR ADD (
  CONSTRAINT LNE_SCHEDULE_HDR_PK
  PRIMARY KEY
  (AGR_NO, START_DATE)
  );
--  USING INDEX TBG.LNE_SCHEDULE_HDR_PK
--  ENABLE NOVALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON TBG.LNE_SCHEDULE_HDR TO TBG;

select count(*) from "TBG"."LNE_SCHEDULE_HDR_OLD";
select count(*) from "TBG"."LNE_SCHEDULE_HDR";
insert into "TBG"."LNE_SCHEDULE_HDR" select * from  "TBG"."LNE_SCHEDULE_HDR_OLD";
commit;

drop table "TBG"."LNE_SCHEDULE_HDR";
alter table TBG.LNE_SCHEDULE_HDR_OLD rename to LNE_SCHEDULE_HDR;

--drop table "PROKUNIN_DBA"."LNE_SCHEDULE_HDR";
  CREATE TABLE "PROKUNIN_DBA"."LNE_SCHEDULE_HDR" 
   (	"BRANCH" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"AGR_NO" NUMBER NOT NULL ENABLE, 
	"START_DATE" DATE NOT NULL ENABLE, 
	"SCHEDULE_TYPE_C" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"REMAINDER" NUMBER NOT NULL ENABLE, 
	"PARENT_DATE" DATE, 
	"DOSR_DATE" DATE, 
	"UPDATED" TIMESTAMP (6) DEFAULT LOCALTIMESTAMP, 
	"UPDATED_BY" VARCHAR2(30 CHAR) DEFAULT coalesce(sys_context('userenv','client_identifier'), user), 
	"PRC_CALC_MODE" VARCHAR2(30 CHAR), 
	"SCHED_TYPE" VARCHAR2(30 CHAR), 
	"EFFECT_RATE" NUMBER, 
	"PSK" NUMBER, 
	"ACT_PAY_FLAG" VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL ENABLE, 
	"GR_CODE" VARCHAR2(30 CHAR), 
	"EFFECT_RATE_2" NUMBER, 
	"LOST_INCOME" VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL ENABLE, 
	"PRC_CALC_DATE" DATE, 
	"EXT_FLAG" VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL ENABLE, 
	"EDIT_COND" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"EDIT_PSK" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"EP" NUMBER, 
	"MIDDLE_PAYMENT" NUMBER, 
	"RESTRUCT_FLAG" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"INDIV_PSK" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"HDR_ID" NUMBER DEFAULT null NOT NULL ENABLE, 
	"LAST_PMT_DATE" DATE, 
	 CONSTRAINT "LNE_SCHEDULE_HDR_PK" PRIMARY KEY ("AGR_NO", "START_DATE")
   ) ;
grant insert, update, delete on "PROKUNIN_DBA"."LNE_SCHEDULE_HDR" to tbg;

select * from "PROKUNIN_DBA"."LNE_SCHEDULE_HDR";
grant update any table to tbg;

trunvate table 

select * from TBG.LNE_SUM_TYPE_CODE_C;
select count(*) from "TBG"."LNE_SCHEDULE_HDR";
select max(UPDATED) from TBG.LNE_SCHEDULE_HDR;
select * from "TBG"."LNE_SCHEDULE_HDR" where UPDATED > TO_TIMESTAMP('2023-04-24 13:36:47', 'YYYY-MM-DD HH24:MI:SS');
select * from "TBG"."LNE_SCHEDULE_HDR" where agr_no=33442;
