  CREATE TABLE "TBG"."LNE_SCHEDULE_HDR" 
   (	"BRANCH" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"AGR_NO" NUMBER NOT NULL ENABLE, 
	"START_DATE" DATE NOT NULL ENABLE, 
	"SCHEDULE_TYPE_C" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"REMAINDER" NUMBER NOT NULL ENABLE, 
	"PARENT_DATE" DATE, 
	"DOSR_DATE" DATE, 
	"UPDATED" TIMESTAMP (6) DEFAULT LOCALTIMESTAMP, 
	"UPDATED_BY" VARCHAR2(30 CHAR) DEFAULT coalesce(sys_context('userenv','client_identifier'), user), 
	"PRC_CALC_MODE" VARCHAR2(30 CHAR), 
	"SCHED_TYPE" VARCHAR2(30 CHAR), 
	"EFFECT_RATE" NUMBER, 
	"PSK" NUMBER, 
	"ACT_PAY_FLAG" VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL ENABLE, 
	"GR_CODE" VARCHAR2(30 CHAR), 
	"EFFECT_RATE_2" NUMBER, 
	"LOST_INCOME" VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL ENABLE, 
	"PRC_CALC_DATE" DATE, 
	"EXT_FLAG" VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL ENABLE, 
	"EDIT_COND" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"EDIT_PSK" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"EP" NUMBER, 
	"MIDDLE_PAYMENT" NUMBER, 
	"RESTRUCT_FLAG" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"INDIV_PSK" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"HDR_ID" NUMBER DEFAULT null NOT NULL ENABLE, 
	"LAST_PMT_DATE" DATE, 
	 CONSTRAINT "LNE_SCHEDULE_HDR_PK" PRIMARY KEY ("AGR_NO", "START_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_BELL_TABLE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_BELL_TABLE" ;
